version: '3.8'

volumes:
  db-data:

services:
  node-api:
    container_name: node-api
    build:
      context: "."
      dockerfile: "Dockerfile.dev"
    tty: true
    stdin_open: true
    restart: always
    ports:
      - '3000:3000'
    volumes:
      - '.:/node-api'
    depends_on:
      - mysql-db
    links:
      - mysql-db
    env_file:
      - .env.dev
    environment:
      - DB_HOST=mysql-db

  mysql-db:
    container_name: mysql-db
    image: mysql:8.0.28
    restart: always
    ports:
      - '3333:3306'
    volumes:
      - 'db-data:/var/lib/mysql'
    env_file:
      - .env.dev
    environment:
      MYSQL_ROOT_PASSWORD: '${DB_PASSWORD}'
      MYSQL_DATABASE: '${DB_DBNAME}'
      MYSQL_USER: '${DB_USERNAME}'
      MYSQL_PASSWORD: '${DB_PASSWORD}'
      TZ: "Asia/Tokyo"
    command: mysqld --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
