name: e2e-test
on:
  push:
    branches:
      - develop
jobs:
  run-e2e-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          ref: ${{ github.event.pull_request.head.sha }}

      - name: Cache node_modules
        id: node_modules_cache_id
        uses: actions/cache@v2
        with:
          path: node_modules
          key: ${{ runner.os }}-node_modules-${{ hashFiles('**/package-lock.json') }}

      - name: Cache node_modules
        id: node_modules_cache_id
        uses: actions/cache@v2
        with:
          path: node_modules
          key: ${{ runner.os }}-node_modules-${{ hashFiles('**/package-lock.json') }}

      - name: Cache node_modules
        id: node_modules_cache_id
        uses: actions/cache@v2
        with:
          path: node_modules
          key: ${{ runner.os }}-node_modules-${{ hashFiles('**/package-lock.json') }}

      - name: Create .env.test file
        run: |
          echo "${{ secrets.TEST_ENV_FILE }}" > .env.test

      - name: Run test on docker compose
        if: steps.node_modules_cache_id.outputs.cache-hit != 'true'
        run: |
          docker compose --env-file .env.test -f docker-compose.test.yml up --build --abort-on-container-exit
        working-directory: ./
