name: e2e-test
on:
  push:
    branches:
      - develop
jobs:
  run-e2e-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Cache
        uses: actions/setup-node@v3
        id: setup-node-id
        with:
          node-version: 18
          cache: npm

      - name: Install dependencies
      - if: ${{ steps.setup-node-id.outputs.cache-hit != 'true' }}
        run: npm install
      - run: npm ls --depth=0

      - name: Create .env.test file
        run: |
          echo "${{ secrets.TEST_ENV_FILE }}" > .env.test

      - name: Run test on docker compose
        run: |
          docker compose --env-file .env.test -f docker-compose.test.yml build
          docker compose --env-file .env.test -f docker-compose.test.yml up
        working-directory: ./
