name: e2e-test
on:
  push:
    branches:
      - develop
jobs:
  run-e2e-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup
        uses: actions/setup-node@v3
        id: setup_node_id
        with:
          node-version: 18

      - name: Cache
        uses: actions/cache@v3
        id: node_modules_cache_id
        env:
          cache-name: cache-node-modules
        with:
          path: '**/node_modules'
          key: ${{ runner.os }}-build-${{ env.cache-name }}-${{ hashFiles('**/package-lock.json') }}
      - if: ${{ steps.setup_node_id.outputs.cache-hit != 'true' }}
        run: npm install

      - name: Create .env.test file
        shell: bash
        env:
          DB_PASSWORD: ${{ secrets.DB_PASSWORD }}
          DB_DBNAME: ${{ secrets.DB_DBNAME }}
          DB_USERNAME: ${{ secrets.DB_USERNAME }}
          DB_PORT: ${{ secrets.DB_PORT }}
          DB_HOST: ${{ secrets.DB_HOST }}
        run: |
          echo DB_PASSWORD="$DB_PASSWORD" >> .env.test
          echo DB_DBNAME="$DB_DBNAME" >> .env.test
          echo DB_USERNAME="$DB_USERNAME" >> .env.test
          echo DB_PORT="$DB_PORT" >> .env.test
          echo DB_HOST="$DB_HOST" >> .env.test

      - name: Run test on docker compose
        run: |
          docker compose --env-file .env.test -f docker-compose.test.yml build
          docker compose --env-file .env.test -f docker-compose.test.yml up --abort-on-container-exit
        working-directory: ./
