name: e2e-test
on:
  push:
    branches:
      - develop
jobs:
  run-e2e-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Create .env.test file
        run: |
          echo "${{ secrets.TEST_ENV_FILE }}" > .env.test

      - name: Run test on docker compose
        run: |
          docker compose --env-file .env.test -f docker-compose.test.yml up -d
          docker compose --env-file .env.test -f docker-compose.test.yml exec test-node-api ls
        working-directory: ./
